title: Robert Johnson
#logo: /assets/img/headshot_circle.png
logo: photo-circle.png
#description: text below image
#show_downloads: true
description:    
  A customer-centric Software Engineer with a history of architecting and building multiple large-scale
  systems. My mission is to create intuitive user experiences that bring delight to the end user and enable them to work more efficiently.
  <br><br>
  <a href="https://www.linkedin.com/in/robert-johnson-69a1869/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> 

theme: jekyll-theme-minimal
