title: Robert Johnson
#logo: /assets/img/headshot_circle.png
logo: photo-circle.png
#description: text below image
#show_downloads: true
description:    
  I am a customer-centric Software Engineer with a proven track record of designing and implementing numerous large-scale systems.
  <br><br>
  My mission is to create intuitive user experiences that not only delight end users but also empower them to significantly enhance their productivity.
  <br><br>
  <a href="https://github.com/robjkc/robjkc.github.io/Robert-Johnson.pdf"><img src="https://img.shields.io/badge/Resume-View%20Resume-brightgreen?logo=adobe-acrobat-reader"></a>
  <br><br>
  <a href="https://www.linkedin.com/in/robert-johnson-69a1869/" target="_blank"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> 
  <br><br>
  <a href="mailto:robjkc@gmail.com"> <img src="https://img.shields.io/badge/Email-Send%20Email-brightgreen?logo=gmail"> </a>
theme: jekyll-theme-minimal
